### ISSUE TITLE
data

### ISSUE THREAD

**Issue by guojun1992** [antonholmquist/jason#10]
If the amount of data to 50kb, performance testing will be very slow？

**Comment by antonholmquist** [comment]
Okay. Did you try it? I haven't done any proper performance tests so it would be interesting to see if anyone has.

**Comment by antonholmquist** [comment]
I will consider this closed if no more info is given :)

**Comment by antonholmquist** [comment]
Closing.

**Comment by guojun1992** [comment]
I am sorry，Some time ago too busy to reply，I have tested it If the amount of data so big It will be very slow，the speed  about One-third compared with php，I have used C rewrite the json lib。
