### ISSUE TITLE
Any plans to support Updating/Writing JSON?

### ISSUE THREAD

**Issue by treeder** [antonholmquist/jason#16]
Or will it always just be for reading?

**Comment by Annonomus-Penguin** [comment]
+1. Was just going to open this.

You could make this *so* easy to work with by exposing a pointer to the functions that return `*Value`s. For example, I could do this:

```go
//  Build a new object to add
newValue, _ := jason.NewValueFromBytes([]byte("true"))

// Changes a value
object.Map()["keyOne"] = newValue

// Adds a new item
object.Map()["keyTwo"] = newValue
```

It's not pretty, but at least it's something. You would need to have functions to make it easier to directly build values, like this:

```go
func NewValueFromString(str string) *Value
func NewValueFromNull() *Value
// ...
```go

**Comment by antonholmquist** [comment]
Settings values was tried in https://github.com/antonholmquist/jason/issues/12 without success. I have not investigated this further.

**Comment by antonholmquist** [comment]
Closing this
